name: Newsletter automation

on:
  workflow_dispatch:
    inputs:
      dummy:
        description: 'Ce repo public ne contient pas les secrets nécessaires. Utiliser le repo privé.'
        required: false

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: echo "Les workflows actifs sont dans le repo privé uniquement."
